// This file is generated by Slice Machine. Update with care!

import ProjectCard from './ProjectCard';
import ProjectPage from './ProjectPage';
import ResumeEducationSlice from './ResumeEducationSlice';
import ResumeExperienceSlice from './ResumeExperienceSlice';
import ResumeSlice from './ResumeSlice';
import ResumeTitle from './ResumeTitle';

export {
	ProjectCard,
	ProjectPage,
	ResumeEducationSlice,
	ResumeExperienceSlice,
	ResumeSlice,
	ResumeTitle,
};

export const components = {
	project_card: ProjectCard,
	project_page: ProjectPage,
	resume_education_slice: ResumeEducationSlice,
	resume_experience_slice: ResumeExperienceSlice,
	resume_slice: ResumeSlice,
	resume_title: ResumeTitle,
};
