// This file is generated by Slice Machine. Update with care!

import ProjectCard from './ProjectCard';
import ProjectPage from './ProjectPage';

export {
	ProjectCard,
	ProjectPage,
};

export const components = {
	project_card: ProjectCard,
	project_page: ProjectPage,
};
